title: O:se Kenhionhata:tie Land Back Camp
logo: landbackcamplogo.webp
mailjet_key_public: 69b1cf6644e2394384445ff8726358a4
mailjet_key_secret: 740b362bf808b1f9175ce13fb09d540d
mailjet_email_from: ose.kenhionhatatie@gmail.com
password: >
  $2y$10$lrW38FlNt77Gs9eH0eKMZ.CrHANRLIFEok7pp8GCrrERgWUDrsfwa
